name: Update Repository

on:
  repository_dispatch:
  types: [kick]

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        run: |
          ./gen.sh
