name: Update Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [kick]

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Version (Workflow Dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo VERSION=${{ inputs.version }} >> $GITHUB_ENV
      - name: Set Version (Repository Dispatch)
        if: github.event_name == 'repository_dispatch'
        run: |
          echo VERSION=${{ github.event.client_payload.version }} >> $GITHUB_ENV
      - run: |
          echo "Version: $VERSION"
      - name: Generate
        run: |
          ./gen.sh
      - name: Add HTML Update
        run: |
          git add index.html
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git commit -m "Regenerated HTML for version ${VERSION}"
          git push
      
